export const textConstants = {

    //Terms and conditions

    text1:"THE FOLLOWINGS ARE THE TERMS & CONDITIONS BY WHICH THIS WEBSITE IS REGULATED. IF YOU ARE USING THIS WEBSITE, YOU SHALL BE BOUND BY THE TERMS AND CONDITIONS LAID OUT IN THIS END-USER AGREEMENT.",
    text2:"PLEASE READ THIS END-USER AGREEMENT CAREFULLY. For Ages above 18+ only.",
    text3:"This End User Agreement governs your use of www.ludoempire.com Ludo Empire, its mobile game applications, its website, its software, their associated upgrades, patches, and updates and related services (the Products or Services) currently provided or which will be provided by FABZEN TECHNOLOGIES PRIVATE LIMITED.",
    text4:"Any person (User) utilizing www.ludoempire.com or Ludo Empire App for availing of the online gaming services offered therein or participating in the various tournaments and games, being conducted on Ludo Empire shall be bound by these Terms and Conditions, and all other rules, regulations and terms of use referred to herein or provided by Ludo Empire in relation to any Ludo Empire's Services.",
    text5:"Ludo Empire shall be entitled to modify these Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by Ludo Empire in relation to any Ludo Empire's Services at any time, by posting the same on the Ludo Empire App or the website. Use of Ludo Empire constitutes the User's acceptance of such Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by Ludo Empire in relation to any Ludo Empire's Services, as may be amended from time to time. Ludo Empire may also notify the user of any change or modification in these Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by Ludo Empire, by way of sending an email to the User's registered email address or posting notifications in the User accounts. The User may then exercise the options provided in such an email or notification to indicate non-acceptance of the modified Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by Ludo Empire. If such options are not exercised by the User within the time frame prescribed in the email or notification, the User will be deemed to have accepted the modified Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by Ludo Empire.",
    text6:"Certain Ludo Empire Services being provided on Ludo Empire may be subject to additional rules and regulations set down in that respect. To the extent that these Terms and Conditions are inconsistent with the additional conditions set down, the additional conditions shall prevail.",
    text7:"TO ENTER INTO THIS END USER AGREEMENT, YOU MUST BE AN ADULT OF THE LEGAL AGE OF MAJORITY IN INDIA AND NOT FROM ANY OF THE FOLLOWING STATES WHICH HAVE BANNED ALL TYPES OF REAL MONEY GAMES. THAT YOU ARE LEGALLY AND FINANCIALLY RESPONSIBLE FOR ALL ACTIONS USING OR ACCESSING OUR SOFTWARE, INCLUDING THE ACTIONS OF ANYONE YOU ALLOW TO ACCESS TO YOUR ACCOUNT. YOU AFFIRM THAT YOU HAVE REACHED THE LEGAL AGE OF MAJORITY, AND UNDERSTAND AND ACCEPT THIS AGREEMENT (INCLUDING ITS DISPUTE RESOLUTION TERMS).",
    text8:"IF YOU ARE UNDER THE LEGAL AGE OF MAJORITY, YOU ARE NOT ELIGIBLE TO ENTER THIS AGREEMENT. PLEASE STOP USING THIS WEBSITE IMMEDIATELY.",
    text9:"If you continue using this website or the Software and its Services, by downloading or using the Software, you are agreeing to Ludo Empire's Terms of Service and acknowledge that you have read its Privacy Policy.",
    text10:"Certain words or phrases are defined to have certain meanings when used in this Agreement. Those words and phrases are defined below in Section 24.",
    ownership:"All title, ownership rights and intellectual property rights in and to the Products (including, without limitation, all text, graphics, music or sounds, all messages or items of information, fictional characters, names, themes, objects, scenery, costumes, effects, slogans, places, characters, diagrams, concepts, choreographies, videos, audio-visual effects, domain names and any other elements which are part of the Products, individually or in combination) and any and all copies thereof are owned by Fabzen Technologies Pvt Ltd. . The Products are protected by national and international laws, copyright treaties and conventions and other laws.",
    
    license1:"Ludo Empire grants you a personal, non-exclusive, non-transferable, non-sublicensable limited right and license to install and/or use the Product and Services for your personal, non-commercial use (the  License) for such time until either You or Ludo Empire terminates this EUA. The rights that www.ludoempire.com grants you under the License are subject to the terms of this Agreement, and you may only make use of the License if you comply with all applicable terms. Updates, upgrades, patches, and modifications may be necessary in order to be able to continue to use the Products on certain hardware. The License becomes effective on the date you accept this Agreement. The Mobile Software is licensed, not sold, to you; the License does not grant you any title or ownership in the Software.",
    license2:"As applicable, certain parts of the Products may be using third-party features, some of which are managed by third-party providers for which additional terms and/or costs may apply. Please follow clause 12 for the same.",

    licenseCondition:"3.1 You are not permitted to do any of the following with respect to the Products or any of their parts:",
    licensePoint1:"\u25C9 use them commercially or for a promotional purpose;",
    licensePoint2:"\u25C9 copy, reproduce, display, perform, or otherwise use them in a way that is not expressly authorized in this Agreement or its Specific Terms;",
    licensePoint3:"\u25C9 sell your account or otherwise transfer winnings to any third party;",
    licensePoint4:"\u25C9 reverse engineer, derive source code from, modify, adapt, translate, decompile, or disassemble them or make derivative works based on them;",
    licensePoint5:"\u25C9 remove, disable, circumvent, or modify any proprietary notice or label or security technology included in them;",
    licensePoint6:"\u25C9 create, develop, distribute, or use any unauthorized software programs to gain an advantage in the online game modes;",
    licensePoint7:"\u25C9 use them to infringe or violate the rights of any third party, including but not limited to any intellectual property, publicity, or privacy rights;",
    licensePoint8:"\u25C9 use, export, or re-export them in violation of any applicable law or regulation; or",
    licensePoint9:"\u25C9 behave in a manner which is detrimental to the enjoyment of the Software or the Services by other users as intended by Ludo Empire, in their sole judgment, including but not limited to the following - cheating, harassment, use of abusive or offensive language, game abandonment, game sabotage, spamming, social engineering, or scamming.",
    

    licenseCondition2:"3.2 While using the Products, you agree to comply with all applicable laws, rules and regulations. You also agree to comply with certain rules of conduct that govern your use of the Products, which are not meant to be exhaustive and can be modified at any time by Fabzen. In all cases, you may only use the Products according to the anticipated use of the Products. For example, for purposes, and without limiting Fabzen's rights to take action against You, You may not:",
    ConditionToPoint1:"\u25C9 create, use, share and/or publish by any means in relation to the Products' any material (text, words, images, sounds, videos, etc.) which would breach a duty of confidentiality, infringe any intellectual property right or an individual's right to privacy or which would incite the committing of an unlawful act (in particular, piracy, cracking, or circulation of counterfeit software);",
    ConditionToPoint2:"\u25C9 modify, distort, block, abnormally burden, disrupt, slow down and/or hinder the normal functioning of all or part of the software, or their accessibility to other users, or the functioning of the partner networks of the Products, or attempt to do any of the above;",
    ConditionToPoint3:"\u25C9 transmit or propagate any virus, trojan horse, worm, bomb, corrupted file and/or similar destructive device or corrupted data in relation to the Products, and/or organise, participate in, or be involved in any way in an attack on Fabzen's servers and/or the Products and/or those of their service providers and partners;",
    ConditionToPoint4:"\u25C9 create, supply, or use alternative methods of using the Products, for example, server emulators;",
    ConditionToPoint5:"\u25C9 spamming chat, whether for personal or commercial purposes, by disrupting the flow of conversation with repeated postings of a similar nature;",
    ConditionToPoint6:"\u25C9 transmitting or communicating any material or content which, in the sole and exclusive discretion of Fabzen, is believed or deemed offensive, including, but not limited to, language that is harmful, threatening, unlawful, abusive, harassing, defamatory, disparaging, obscene, sexually explicit, or racially, ethnically, or otherwise objectionable;",
    ConditionToPoint7:"\u25C9 harassing or threatening any other users of the Products;",
    ConditionToPoint8:"\u25C9 make inappropriate use of the help service or the claim buttons or send untruthful reports to members of Fabzen's personnel;",
    ConditionToPoint9:"\u25C9 falsely claim to be an employee or representative of Fabzen or its partners and/or agents;",
    ConditionToPoint10:"\u25C9 falsely claim an endorsement in connection with the Products or with Fabzen.",
    
    licenseLast:"Any non-compliance by you with this Clause may also be a violation of our or third parties' intellectual property and other proprietary rights, which may subject you to civil liability and/or criminal prosecution.",
   

    UsAge:"If we suspect that you are or receive notification that you are currently under 18 years or were under 18 years (or below the age of majority as stipulated in the laws of the jurisdiction applicable to you) when you played any game through our Service, your Account will be suspended (locked) to prevent you from playing further or making any withdrawals from your Account. We will then investigate the matter, including whether you have been playing the game as an agent for, or otherwise on behalf, of a person under 18 years (or below the age of majority as stipulated in the laws of the jurisdiction applicable to you). If, having found that you: (a) are currently; (b) were under 18 years or below the majority age which applies to you at the relevant time; or (c) have been at the behest of a person under 18 years or below the majority age, wherein:",
    UsAgePoint1:"\u25C9 all winnings currently or due to be credited to your Account will be retained;",
    UsAgePoint2:"\u25C9 all winnings gained from playing through the Service whilst acting as an agent to someone underage must be paid to us on demand (if you fail to comply with this provision, we will seek to recover all costs associated with recovery of such sums); and/or",
    UsAgePoint3:"\u25C9 any monies deposited in your Account which are not winnings will be returned to you OR retained until you turn 18 years old at our sole discretion. We reserve the right to deduct payment transaction fees from the amount to return, including maintenance fees for deposits to your account, which we may retain.",
    UsAgeLast:"In the event we suspect you are in breach of the provisions of this Clause or are attempting to rely on them for a fraudulent purpose, we reserve the right to take any action necessary in order to investigate the matter, including informing the relevant law enforcement agencies.",

    UserConduct:"Users agree to abide by the following stipulated rules, regulations, and terms of use of the Website. In the event, that the User does not abide by these following rules, regulations, and terms of use, Ludo Empire may, at its sole and absolute discretion, take necessary remedial action, including but not limited to, restricting, suspending, or terminating any User's access to all or any part of Ludo Empire's Services;",

    conductPoint1:"\u25C9 Deactivating or deleting a user's account and all related information and files on the account. Any amount remaining unused in the User's Game account or Winnings Account on the date of deactivation or deletion shall be transferred to the User's bank account on record with Ludo Empire, subject to a processing fee (if any) applicable on such transfers as set out herein; or",
    conductPoint2:"\u25C9 refraining from awarding any prize(s) to such User.",
    conductPoint3:"\u25C9 Users agree to provide true, accurate, current, and complete information at the time of registration and at all other times (as required by Ludo Empire). Users further agree to update and keep updated their registration information.",
    conductPoint4:"\u25C9 A User shall not register or operate more than one User account with Ludo Empire.",
    conductPoint5:"\u25C9 Users agree to ensure that they can receive all communication from Ludo Empire by marking emails from Ludo Empire as part of their (safe senders) list. Ludo Empire shall not be held liable if any email remains unread by a User as a result of such e-mail getting delivered to the User's junk or spam folder.",
    conductPoint6:"\u25C9 Any password issued by Ludo Empire to a User may not be revealed to anyone else. Users may not use anyone else's password. Users are responsible for maintaining the confidentiality of their accounts and passwords. Users agree to immediately notify Ludo Empire of any unauthorized use of their passwords or accounts or any other breach of security.",
    conductPoint7:"\u25C9 Users agree to exit/log out of their accounts at the end of each session. Ludo Empire shall not be responsible for any loss or damage that may result if the User fails to comply with these requirements.",
    conductPoint8:"\u25C9 Users agree not to use cheats, exploits, automation, software, bots, hacks, or any unauthorized third-party software designed to modify or interfere with Ludo Empire's Services and/or Ludo Empire experience or assist in such activity.",
    conductPoint9:"\u25C9 Users agree not to copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer, grant a security interest in, or otherwise transfer any right to the technology or software underlying Ludo Empire or Ludo Empire's Services.",
    conductPoint10:"\u25C9 Users agree not to disrupt, overburden, or aid or assist in the disruption or overburdening of (1) any computer or server used to offer or support Ludo Empire or the Ludo Empire's Services (each a Server); or (2) the enjoyment of Ludo Empire's Services by any other User or person",
    conductPoint11:"\u25C9 Users agree not to institute, assist or become involved in any type of attack, including without limitation, distribution of a virus, denial of service, or other attempts to disrupt Ludo Empire's Services or any other person's use or enjoyment of Ludo Empire's Services.",
    conductPoint12:"\u25C9 Users shall not attempt to gain unauthorized access to the User accounts, Servers or networks connected to Ludo Empire's Services by any means other than the User interface provided by Ludo Empire, including but not limited to, circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that underlies or is part of Ludo Empire's Services.",

    UserMid:"Without limiting the foregoing, Users agree not to use Ludo Empire for any of the following:",
    UserMid1:"\u25C9 To engage in any obscene, offensive, indecent, racial, communal, anti-national, objectionable, defamatory, or abusive action or communication;",
    UserMid2:"\u25C9 To harass, stalk, threaten, or otherwise violate any legal rights of other individuals;",
    UserMid3:"\u25C9 To publish, post, upload, e-mail, distribute, or disseminate (collectively, Transmit) any inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful content;",
    UserMid4:"\u25C9 To Transmit files that contain viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another person's computer, Ludo Empire, any software, hardware, or telecommunications equipment;",
    UserMid5:"\u25C9 To advertise, engage in or execute any contingent agreement with the outcomes of Ludo Empire;",
    UserMid6:"\u25C9 To Transmit content regarding services, products, surveys, contests, pyramid schemes, spam, unsolicited advertising or promotional materials, or chain letters;",
    UserMid7:"\u25C9 To advertise, offer or sell any goods or services for any commercial purpose claiming to be from Ludo Empire without the express written consent of Ludo Empire;",
    UserMid8:"\u25C9 To download any file, recompile or disassemble or otherwise affect our products that you know or reasonably should know cannot be legally obtained in such manner;",
    UserMid9:"\u25C9 To falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or the source of software or other material;",
    UserMid10:"\u25C9 To restrict or inhibit any other user from using and enjoying any public area within our sites;",
    UserMid11:"\u25C9 To collect or store personal information about other Users;",
    UserMid12:"\u25C9 To interfere with or disrupt Ludo Empire, servers, or networks;",
    UserMid13:"\u25C9 To impersonate any person or entity, including, but not limited to, a representative of Ludo Empire, or falsely state or otherwise misrepresent User's affiliation with a person or entity;",
    UserMid14:"\u25C9 To forge headers or manipulate identifiers or other data in order to disguise the origin of any content transmitted through Ludo Empire or to manipulate the User's presence on Ludo Empire;",
    UserMid15:"\u25C9 To take any action that imposes an unreasonably or disproportionately large load on our infrastructure;",
    UserMid16:"\u25C9 To engage in any illegal activities. You agree to use our bulletin board services, chat areas, news groups, forums, communities and/or message or communication facilities (collectively, the Forums) only to send and receive messages and material that are proper and related to that particular Forum.",


    UserLast1:"If a User chooses a username that, in Ludo Empire's considered opinion is obscene, indecent, abusive or that might subject Ludo Empire to public disparagement or scorn, Ludo Empire reserves the right, without prior notice to the User, to change such username and intimate the User or delete such username from Ludo Empire, and/or deny such User access to Ludo Empire, or any combination of these options.",
    UserLast2:"Unauthorized access to Ludo Empire is a breach of these Terms and Conditions, and a violation of the law. Users agree not to access Ludo Empire by any means other than through the interface that is provided by Ludo Empire for use in accessing Ludo Empire. Users agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of our app.",
    UserLast3:"The use of Ludo Empire is subject to existing laws and legal processes. Nothing contained in these Terms and Conditions shall limit Ludo Empire's right to comply with government, court, and law-enforcement requests or requirements relating to Users' usage of Ludo Empire.",
    UserLast4:"Users may contact Ludo Empire's Helpdesk with problems or questions, as appropriate.",
    UserLast5:"Persons below the age of eighteen (18) years are not allowed to play/register/use any of the Ludo Empire & consequent participation in any activity on Ludo Empire is not permitted and such person is subject to disqualification at the sole and absolute discretion of Ludo Empire, whenever it comes to the knowledge of Ludo Empire.",
    

    Play1:"Ludo Empire may involve an element of financial risk and may be habit-forming. Please play responsibly and at your own risk.",
    Play2:"During gameplay, please be aware of your surroundings and play safely. You agree that your use of the apps and play of the games is at your own risk, and it is your responsibility to maintain such health, liability, medical life, and other insurance policies as you deem reasonably necessary for any injuries that you may incur while using the services. You also agree not to use the Apps to violate any applicable law, rule, or regulation or the guidelines and how to play, and you agree not to encourage or enable any other individual to violate any applicable law, rule or regulation, or the guidelines. Without limiting the foregoing, you agree that in conjunction with your use of the Apps, you will not inflict emotional distress on other people, will not humiliate other people (publicly or otherwise), will not assault, or threaten people, will not impersonate any other person or misrepresent your affiliation, title or authority, and will not otherwise engage in activity that may result in injury, self-harm, habit-forming patterns, and/or liability of any kind. Ludo Empire and its developers disclaim liability related to injury, self-harm, and/or habit-forming patterns that may occur during your use of our services, including any claims based on the violation of any applicable law, rule or regulation or your alleged negligence or other tort liability.",
    Play3:"If you believe that you are forming a habit of gaming which is problematic, notify Ludo Empire by email or through the in-game live Hosts, if provided. Ludo Empire policy does not provide you with an option to self-set or change deposit limits at your discretion; rather your identity will be confirmed, and your account will be closed for real money gaming activity, for a prescribed period. Ludo Empire reserves the absolute right, to itself, to review or use third-party verification to review player activity in the Games or as reported by other gaming operators to profile and remove a player's access in its sole discretion.",
    Play4:"These are some general guidelines that can help make your playing experience safer, and avoid the risk that you may indulge in excessive gaming and addiction:",


    PlayToPoint1:"\u25C9 Add money to the Ludo Empire's Wallets only with money that you can afford to spend.",
    PlayToPoint2:"\u25C9 Please, never add money to the account Wallets with money that you need for important or essential things such as food, rent, day-to-day bills, medical assistance or education.",
    PlayToPoint3:"\u25C9 Pre-plan your purchases and the time you will spend playing on the Websites and stick to that limit, regardless of your performance.",
    PlayToPoint4:"\u25C9 Do not play when you are upset, tired, or depressed. It is difficult to make good decisions when you are not feeling well.",
    PlayToPoint5:"\u25C9 Do not put off personal and other important tasks in order to play. Complete all your important tasks so that you can play with a free and calm mind.",
    PlayToPoint6:"\u25C9 Balance your gameplay duration with other activities.",
    PlayToPoint7:"\u25C9 Do not borrow money in order to make purchases on the Websites.",
    PlayToPoint8:"\u25C9 Avoid using all the monies in the game wallets in a single game or session.",
    PlayToPoint9:"\u25C9 Take time-outs and breaks regularly.",
    PlayToPoint10:"\u25C9 Only participate in games that are commensurate with your competence level and financial capabilities. Do not get tempted to participate in games with high entry fees, despite winning consistently.",



    PlayLast:"Further, in the event that you have a dispute with one or more other users of the apps, or any other third party while using the services, you release Ludo Empire and its developers from all claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, suspected, and unsuspected, disclosed, and undisclosed, arising out of or in a way connected with such disputes.",

  //Privacy

  Privacy:"www.ludoempire.com (Website or Plxsatform) is owned, developed, and operated by Fabzen Technologies Private Limited (Fabzen, we or us).The policies that are mentioned below are applicable to this Website www.ludoempire.com.Please be advised that this Privacy Policy (Policy) applies solely to the information  gathered at our Website and this policy does not apply to any information supplied to other websites whether it is or not affiliated with us. By visiting our website, you (you or user) accept this Privacy Policy, and further, you ensure that you are at least 18 years or above, andauthorized to play Ludo Empire as per the Legal mandates of your residing jurisdiction. If you  disagree with the terms of this Policy, please do not use the Website any further.",


  General:"Ludo Empire and Fabzen are committed to protecting the privacy of their users in all aspects, with a goal to offer the best gaming experience to their users which is both fun and secure. Kindly take a few minutes to read the 'About Us' section to know more. Few of our services are offered for free, though you may need prior registration to participate in the games we offer. The information about the user is collected by Ludo Empire from the data supplied only by the users.Before submitting any information to the Platform, kindly read the following Privacy Policy for a detailed explanation of how your personal information shall be treated by us. By utilising the Platform, you give your implied consent towards the use, collection, disclosure, and transfer of your personal information solely for the purposes outlined in this Policy and for the collection, processing, and maintenance of such information. If any part of this Privacy Policy is not acceptable to you, we request you to not use the Platform any further.When you use any part of the Platform, it indicates your implied acceptance of this Policy as well as your consent for us to collect, use and disclose your personal information in accordance with the provisions of this Policy. While you are not obligated to provide us with your personal information and may withdraw your consent to keep us from collecting your personal information, kindly note that in any such event, you will be unable to utilise the vast scope of facilities and services offered to you by us.",

  Information:"We collect information, only voluntarily submitted by our users to the Website in order to assist us in responding to various requests from the respective users. We are dedicated to protecting the privacy of all users of our Website, except as disclosed below. We do not sell, barter, give away, rent, or permit a third party to use your personal information, in the case your data reaches any third parties, the same shall be mentioned down under.",

  Data:"To make use of the vast array of facilities and services  offered on the Platform, users shall be required to provide  certain personal information to complete the registration process. These include:",

  DataPoint1:"In addition to the above information, in the process of providing you with access to the services, and the features offered through the Platform and to verify your identity, you may be required to furnish additional information, including your:",
  DataPoint2:"Ludo Empire shall not collect any information or contact any given number directly for personal use. The purpose behind collecting this information from the users is to ensure the secure transfer of funds from their banks to the in-game wallet and vice versa. Any information you provide will not be used for other commercial purposes and will not be forwarded to any third party for their usage.",
  DataPoint3:"Further details such as your Bank Account Number and KYC details may be collected by or shared with our third-party payment gateway service provider, to verify, and process your transactions. This is required before users can be granted permission to use the Ludo Empire App to their full extent and are given complete access to all the services provided.",
  DataPoint4:"All the information that is required is specific and is related to the kind of services the user wishes to avail or access and such information shall be used solely to provide services, including but not limited to the games provided on Ludo Empire and their features which are requested by the user. The details provided by the users allow us to improve the App and bring you a fun, secure and user-friendly gaming experience. The Platform is permitted to share information provided with their affiliates and other third parties under certain conditions. This is done with the view of complying with legal regulations and guidelines which facilitates a secure network, further ensuring the prevention of fraud or other imminent harm.",
  DataPoint5:"We use third parties, subsidiaries, affiliates, and business partners to perform functions such as transactions, marketing, advertising, remarketing, etc., on our behalf. These entities may be provided limited or full access to the user's personal information which is needed to perform their functions and are under a legal obligation in terms of any personal information collected from this Website. They are restricted from using, selling, distributing, or altering this data in any way other than to provide the requested services to the Website. If you are entering any other website from this website or the application page, then you shall be governed by their respective Privacy Policy and Terms & Conditions.",
  DataPoint6:"We may also use or disclose our user's personal information if required and/or obligated to do so by law or to assist in law enforcement if that is necessary:",

  Cookies1:"Cookies are small files that a site or its service provider transfers to your computer's hard drive through your web browser (only if you allow) that enable the sites or service provider systems to recognize your browser to capture and remember certain information. We use cookies to understand and save your preferences for future visits and compile aggregate data about site traffic and site interaction so that we can offer a better site experience in the future.",
  Cookies2:"Certain information that you provide on the Website may be a part of publicly accessible portions of the Website such as message boards, comments, or feedback sections. This Policy does not apply to any information you choose to make public by posting it on any such parts of the Website. Please be careful about what information you choose to disclose on the publicly accessible portions of the Website.",
  Cookies3:"To improve the effectiveness and usability of the Website for our users, we use (cookies), or similar electronic tools to collect information to assign each visitor a unique random number as a User Identification (User ID) to understand the user's interests using the identified computer. Unless the user voluntarily identifies themselves (e.g., through registration), Ludo Empire has no way of knowing who the user is, even if we assign a cookie to the user's computer. The only personal information a cookie can contain is information supplied by the user. A cookie cannot read data off the user's hard drive. Ludo Empire's advertisers may also assign their cookies to the user's browser, only if the user clicks on their ad banners, a process that Ludo Empire does not control.",
  Cookies4:"Ludo Empire's web servers automatically collect limited information about the user's computer's connection to the Internet, including the user's IP address, when the user visits the Website. (The user's IP address is a number that lets computers attached to the Internet know where to send data to the user -- such as the web pages viewed by the user). The user's IP address does not identify the user personally. Ludo Empire uses this information to deliver its web pages to users upon request, to tailor its Website to the interests of its users, to measure traffic within the Website and to let advertisers know the geographic locations from where Ludo Empire's visitors come.",

  Discolsure1:"Ludo Empire may share information as provided by you and data concerning usage of the amusement facility and participation in the games with third-party service providers engaged by Ludo Empire, for data analytics or other similar purposes, like processing data, providing & improving the services and helping Ludo Empire serve you better.",
  Discolsure2:"Ludo Empire shares data with affiliated advertising agents, to utilise the data and provide relevant advertisements to the users only for promotional matters.",
  Discolsure3:"Where we propose to use your personal information (that is, information that may be used to identify the user and that is not otherwise publicly available) for any other uses, we will ensure that we notify you first. You will also be allowed to withhold or withdraw your consent for your use other than as listed above.",
  Discolsure4:"By using the Platform, you hereby expressly agree and grant consent to the collection, use and storage of this information by Ludo Empire. Ludo Empire reserves the right to share, disclose and transfer information collected hereunder with its affiliates solely for the purpose of services availed by Users. Further, Ludo Empire reserves the right to disclose personal information as obligated by law, in response to duly authorized legal processes, and governmental requests, as necessary to protect the rights and interests of Ludo Empire.",

 Links:"Ludo Empire may include links to other websites. Such websites are governed by their respective privacy policies, which are beyond Ludo Empire's control. Once the user leaves Ludo Empire's servers (the user can tell where they are by checking the URL in the location bar on their browser), the use of any information provided by the user is governed by the privacy policy of the operator of the site which the user is visiting. That policy may differ from Ludo Empire's own. If the user cannot find the privacy policy of any of these sites via a link from the site's homepage, the user may contact the site directly for more information. Ludo Empire is not responsible for the privacy practices or the content of such websites.",

DataSecurity:"All information gathered on Ludo Empire is securely stored within the Fabzen-controlled database. The database is stored on servers secured behind a firewall; access to such servers is password-protected and strictly limited based on a need-to-know basis. However, we understand that as effective as our security measures are, no security system is impenetrable. Thus, we do not guarantee the security of our database, nor can we guarantee that the information you supply will not be intercepted while being transmitted to us over the Internet. Further, any information you include in a posting to the discussion areas will be available to anyone with Internet access. By using the Platform, you understand and agree that your information may be used in or transferred to countries other than India.",
DataSecurity1:"We also believe that the internet is an ever-evolving platform. We may periodically review from time to time and change our Privacy Policy to incorporate such future changes as may be considered appropriate, without any notice to you. Our use of any information we gather will always be consistent with the policy under which the information was collected, regardless of what the new policy may be. Any changes to our Policy will be posted on this page, so you are always aware of what information we collect, how we use it, how we store it and under what circumstances we disclose it.",

Advertising1:"Ludo Empire may present information to its online advertisers -- to help them understand our audience and confirm the value of advertising on the Platform-- it is usually in the form of aggregated statistics on traffic to various pages within our site. When you register with Ludo Empire's newsletter, we may contact you from time to time about our games, new content to provide inputs about the amusement facilities or other services availed by you or to inform you of which we believe may benefit you, via in-app push notifications, emails, SMSs",
Advertising2:"We may use the information provided by you, including your email address or phone number, to contact you. Please note that Fabzen employees will never call you for your One Time Password or ask you to visit any external links. Do not fall prey to fraudulent calls, phishing emails etc. If you are still confused about whether or not you were contacted by us, please feel free to contact our customer support for any related queries.",
Advertising3:"Several deceptive emails, websites, blogs etc. claiming to be from or associated with Ludo Empire may be circulating on the Internet. These emails, websites, blogs etc. often include our logo, photos, links, content, or other information. Some emails, websites, blogs etc. call the user to provide their login name, One Time Password, etc., or that the user has won a prize/ gift or provides a method to commit an illegal/unauthorized act or deed or request detailed personal information or a payment of some kind. The sources and contents of these emails, websites, blogs etc. and accompanying materials are in no way associated with Ludo Empire. For your protection, we strongly recommend not responding to those emails or using their websites, blogs etc.",

ConditionUse1:"Ludo Empire does not warrant that this Platform, its services, or email sent by us or on our behalf will be free from virus attacks. On such event, Ludo Empire will not be liable for any damages of any kind arising from the use of this portal, including, but not limited to compensatory, direct, indirect, incidental, punitive, special, and consequential damages, loss of data, goodwill, business opportunity, income or profit, loss of or damage to property and claims of third-party. In no event will Ludo Empire be liable for any damage that is over in an amount of INR. 100/-.",
ConditionUse2:"Guidelines for Children: Anyone under the age of 18, is not allowed by law to use the services of this Platform, and if there is any issue that arises from this, it shall be null and void.",

Retention:"Your personal information may be retained and may continue to be stored with us for a lifetime until (i) the relevant purposes for the use of your information described in this Privacy Policy are no longer applicable to us, or; (ii) You email us at support@ludoempire.com and explicitly ask us to erase all your data on demand; or (iii) we are no longer required by applicable law, regulations, contractual obligations, or legitimate business purposes to retain your personal information or retention of your personal information is not required for the establishment, exercise, or defence of any legal claim.",

Applicable:"By visiting this Portal, you agree that the laws of India, and respective jurisdictions, without regard to its conflict of laws, and principles, govern this Privacy Policy and any dispute arising in respect hereof shall be subject to and governed by the Alternative Dispute Resolution process set out in the Terms and Conditions.",

UpdatingInfo:"You will promptly notify Ludo Empire if there are any changes, updates, or modifications to your information. Further, you may also review, update, or modify your information and user preferences by logging into your Profile page on the Platform.",


//Refund

UserRefund:"www.ludoempire.com (Website or Platform) is owned, developed, and operated by Fabzen Technologies Private Limited (Fabzen, we or us). The policies that are mentioned below are applicable to this Website www.ludoempire.com. Please be advised that this Privacy Policy (Policy) applies solely to the information gathered at our Website and this policy does not apply to any information supplied to other websites whether it is or not affiliated with us. By visiting our website, you (you or user) accept this Privacy Policy, and further, you ensure that you are at least 18 years or above, and authorized to play Ludo Empire as per the Legal mandates of your residing jurisdiction. If you disagree with the terms of this Policy, please do not use the Website any further.",

Account:"In the event you would like to cancel your subscription with Ludo Empire, please write to us at support@ludoempire.com from your registered email ID. Your win wallet and main wallet balance (called 'account balance') will then be refunded to the payment method of your choice. Please be informed that certain payment methods may attract additional processing fees that will be deducted from your account balance. We'll also deduct all kinds of bonuses or incentives we ever offered you from your account balance. Because you're cancelling your account with us, we'll have to deactivate the same to prevent you from participating in any of our contests. If you however would like to become a member with us again in future, feel free to contact us first.",

Technical:"We trust our product so much that we 100% guarantee to refund your money either due to an error or mistake in the transaction or in case you end up having to lose any of our contests solely because of technical problems in our App. We however will need sufficient evidence from you to investigate the issue, upon investigation, if it is proved that the error/issue is technical we'll refund you. Since we strive to make our product the best, we might ask questions to gather your feedback on the error and reproduce the same. Please make sure to provide a valid payment method with sufficient details for us to process your refund. The onus of providing accurate/valid bank/UPI/online wallet ID/credit/debit card details is with you. We'll provide you with the refund transaction and reference number thereof in an email sent to you shortly after the refund transaction is successfully submitted at our end. Please allow 48 hours to receive the refund, in case you still have not received the refund, please contact us immediately. Only the entry fee of the contest deducted from your wallet/account will be refunded but not the total estimated winning amount of the contest under the assumption that the requested user has the highest probability of winning the contest, therefore the maximum refund will be your entry fee deducted from your wallet.",

Service:"Ludo Empire is not responsible for any loss resulting from the cancellation of any games due to service outages caused by the failures of our service providers, computer viruses, natural disasters or any other reason that is beyond our control. You acknowledge that you will not be entitled to any refund due to the cancellation of games caused by factors that are beyond the reasonable control of Ludo Empire.",

Failed:"Ludo Empire has the right to check or validate the personal information of the players from time to time. The process of validation can be done through a phone call or via email. If we are not able to get in touch with you at first, several attempts will be made to establish contact with you. In the event that the validation is unsuccessful, or we are unable to contact you after making all possible attempts, we reserve the right to suspend your account and refund the amount lying in your account to the financial instrument/payment platform that you used to make the payment online.",

Cancellation:"Ludo Empire contests, offers, bonuses, tournaments and games may get cancelled or discontinued at any moment without any prior notice. Ludo Empire disclaims any liability, except the refund of the entry fee wherever applicable.",

Termination:"You may cease to use our gaming services and terminate your account by emailing us at support@ludoempire.com with a clear explanation of your intention and duration from 48 hours to 6 months. After evaluating your case, at our discretion, www.ludoempire.com will refund your account balance minus any bonuses, incentives or promotional offers credited to your account within 10 working days and terminate your account. Please note, that any account actions you take after emailing your request for terminating your account, including, but not limited to, playing cash games, tournaments, depositing and withdrawing money, will be deemed as actions taken solely by you and Ludo Empire shall not be responsible for your actions.",

Inactive:"If your account has been inactive for over 365 days and has an unused balance, Ludo Empire shall remind you two times to activate your account. To activate your account, you must log in and use your cash balance by playing a cash game. After the reminders, if you do not activate your account. your cash balance shall be forfeited to Ludo Empire. All reminders shall be sent to the email or phone number listed on your profile, as part of the account details and information you submitted to Ludo Empire. Any account found in breach of our Terms and Conditions shall receive no reminders, and the unused funds in such account shall be subject to the terms of our Breach and Consequences policy.",

Support:"Contact Our Support Ludo Empire support team is available to assist you, so please write to us at support@ludoempire.com from your registered email ID and share your concern or issue, our representative will reach out to you to resolve the matter.",


}