import { StyleSheet, Text, View,ScrollView } from 'react-native'
import React from 'react'
import { SafeAreaView } from 'react-native-safe-area-context'
const Terms = () => {
  return (
    <SafeAreaView className="flex-1 bg-primary">
      <ScrollView  className="mt-10 ">
    <View className="items-center justify-center">
      <Text className="text-blue-400 text-2xl font-psemibold">Terms and Conditions</Text>
      <Text className="text-blue-200 text-2xs px-2 my-4 items-center">THE FOLLOWINGS ARE THE TERMS & CONDITIONS BY WHICH THIS WEBSITE IS REGULATED. IF YOU ARE USING THIS WEBSITE, YOU SHALL BE BOUND BY THE TERMS AND CONDITIONS LAID OUT IN THIS END-USER AGREEMENT.</Text>
      <Text className="text-blue-200 text-lg px-2 my-4 items-center">PLEASE READ THIS END-USER AGREEMENT CAREFULLY. For Ages above 18+ only.</Text>
      <Text className="text-blue-200 text-2xs px-2 my-4 items-center">This End User Agreement governs your use of www.ludoempire.com "Ludo Empire", its mobile game applications, its website, its software, their associated upgrades, patches, and updates and related services (the "Products" or "Services") currently provided or which will be provided by FABZEN TECHNOLOGIES PRIVATE LIMITED.</Text>
      <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Any person ("User") utilizing www.ludoempire.com or Ludo Empire App for availing of the online gaming services offered therein or participating in the various tournaments and games, being conducted on Ludo Empire shall be bound by these Terms and Conditions, and all other rules, regulations and terms of use referred to herein or provided by Ludo Empire in relation to any Ludo Empire's Services.</Text>
      <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Ludo Empire shall be entitled to modify these Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by Ludo Empire in relation to any Ludo Empire's Services at any time, by posting the same on the Ludo Empire App or the website. Use of Ludo Empire constitutes the User's acceptance of such Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by Ludo Empire in relation to any Ludo Empire's Services, as may be amended from time to time. Ludo Empire may also notify the user of any change or modification in these Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by Ludo Empire, by way of sending an email to the User's registered email address or posting notifications in the User accounts. The User may then exercise the options provided in such an email or notification to indicate non-acceptance of the modified Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by Ludo Empire. If such options are not exercised by the User within the time frame prescribed in the email or notification, the User will be deemed to have accepted the modified Terms and Conditions, rules, regulations, and terms of use referred to herein or provided by Ludo Empire.</Text>
      <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Certain Ludo Empire Services being provided on Ludo Empire may be subject to additional rules and regulations set down in that respect. To the extent that these Terms and Conditions are inconsistent with the additional conditions set down, the additional conditions shall prevail.</Text>
      <Text className="text-blue-100 text-2xs px-2 my-4 items-center">TO ENTER INTO THIS END USER AGREEMENT, YOU MUST BE AN ADULT OF THE LEGAL AGE OF MAJORITY IN INDIA AND NOT FROM ANY OF THE FOLLOWING STATES WHICH HAVE BANNED ALL TYPES OF REAL MONEY GAMES. THAT YOU ARE LEGALLY AND FINANCIALLY RESPONSIBLE FOR ALL ACTIONS USING OR ACCESSING OUR SOFTWARE, INCLUDING THE ACTIONS OF ANYONE YOU ALLOW TO ACCESS TO YOUR ACCOUNT. YOU AFFIRM THAT YOU HAVE REACHED THE LEGAL AGE OF MAJORITY, AND UNDERSTAND AND ACCEPT THIS AGREEMENT (INCLUDING ITS DISPUTE RESOLUTION TERMS).</Text>
      <Text className="text-blue-200 text-lg px-2 my-4 font-psemibold items-center">IF YOU ARE UNDER THE LEGAL AGE OF MAJORITY, YOU ARE NOT ELIGIBLE TO ENTER THIS AGREEMENT. PLEASE STOP USING THIS WEBSITE IMMEDIATELY.</Text>
      <Text className="text-blue-200 text-2xs px-2 my-4 items-center">If you continue using this website or the Software and its Services, by downloading or using the Software, you are agreeing to Ludo Empire's Terms of Service and acknowledge that you have read its Privacy Policy.</Text>
      <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Certain words or phrases are defined to have certain meanings when used in this Agreement. Those words and phrases are defined below in Section 24.</Text>
      
      
    </View>
    <View className=" justify-center px-3">
    <Text className="text-blue-400 text-2xl font-psemibold">1. OWNERSHIP</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">All title, ownership rights and intellectual property rights in and to the Products (including, without limitation, all text, graphics, music or sounds, all messages or items of information, fictional characters, names, themes, objects, scenery, costumes, effects, slogans, places, characters, diagrams, concepts, choreographies, videos, audio-visual effects, domain names and any other elements which are part of the Products, individually or in combination) and any and all copies thereof are owned by Fabzen Technologies Pvt Ltd. ("Fabzen"). The Products are protected by national and international laws, copyright treaties and conventions and other laws.</Text>
    </View>
    <View className="px-3 justify-center">
    <Text className="text-blue-400 text-2xl font-psemibold">2. LICENSE GRANT</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Ludo Empire grants you a personal, non-exclusive, non-transferable, non-sublicensable limited right and license to install and/or use the Product and Services for your personal, non-commercial use (the " License") for such time until either You or Ludo Empire terminates this EUA. The rights that www.ludoempire.com grants you under the License are subject to the terms of this Agreement, and you may only make use of the License if you comply with all applicable terms. Updates, upgrades, patches, and modifications may be necessary in order to be able to continue to use the Products on certain hardware. The License becomes effective on the date you accept this Agreement. The Mobile Software is licensed, not sold, to you; the License does not grant you any title or ownership in the Software.</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">As applicable, certain parts of the Products may be using third-party features, some of which are managed by third-party providers for which additional terms and/or costs may apply. Please follow clause 12 for the same.</Text>
    </View>
    <View className="px-3 justify-center">
    <Text className="text-blue-400 text-2xl font-psemibold">3. LICENSE CONDITIONS</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">3.1 You are not permitted to do any of the following with respect to the Products or any of their parts:</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 use them commercially or for a promotional purpose;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 copy, reproduce, display, perform, or otherwise use them in a way that is not expressly authorized in this Agreement or its Specific Terms;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 sell your account or otherwise transfer winnings to any third party;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 reverse engineer, derive source code from, modify, adapt, translate, decompile, or disassemble them or make derivative works based on them;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 remove, disable, circumvent, or modify any proprietary notice or label or security technology included in them;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 create, develop, distribute, or use any unauthorized software programs to gain an advantage in the online game modes;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 use them to infringe or violate the rights of any third party, including but not limited to any intellectual property, publicity, or privacy rights;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 use, export, or re-export them in violation of any applicable law or regulation; or`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 behave in a manner which is detrimental to the enjoyment of the Software or the Services by other users as intended by Ludo Empire, in their sole judgment, including but not limited to the following - cheating, harassment, use of abusive or offensive language, game abandonment, game sabotage, spamming, social engineering, or scamming.`}</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">3.2 While using the Products, you agree to comply with all applicable laws, rules and regulations. You also agree to comply with certain rules of conduct that govern your use of the Products, which are not meant to be exhaustive and can be modified at any time by Fabzen. In all cases, you may only use the Products according to the anticipated use of the Products. For example, for purposes, and without limiting Fabzen's rights to take action against You, You may not:</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 create, use, share and/or publish by any means in relation to the Products' any material (text, words, images, sounds, videos, etc.) which would breach a duty of confidentiality, infringe any intellectual property right or an individual's right to privacy or which would incite the committing of an unlawful act (in particular, piracy, cracking, or circulation of counterfeit software);`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 modify, distort, block, abnormally burden, disrupt, slow down and/or hinder the normal functioning of all or part of the software, or their accessibility to other users, or the functioning of the partner networks of the Products, or attempt to do any of the above;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 transmit or propagate any virus, trojan horse, worm, bomb, corrupted file and/or similar destructive device or corrupted data in relation to the Products, and/or organise, participate in, or be involved in any way in an attack on Fabzen's servers and/or the Products and/or those of their service providers and partners;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 create, supply, or use alternative methods of using the Products, for example, server emulators;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 spamming chat, whether for personal or commercial purposes, by disrupting the flow of conversation with repeated postings of a similar nature;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 transmitting or communicating any material or content which, in the sole and exclusive discretion of Fabzen, is believed or deemed offensive, including, but not limited to, language that is harmful, threatening, unlawful, abusive, harassing, defamatory, disparaging, obscene, sexually explicit, or racially, ethnically, or otherwise objectionable;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 harassing or threatening any other users of the Products;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 make inappropriate use of the help service or the claim buttons or send untruthful reports to members of Fabzen's personnel;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 falsely claim to be an employee or representative of Fabzen or its partners and/or agents;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 falsely claim an endorsement in connection with the Products or with Fabzen.`}</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Any non-compliance by you with this Clause may also be a violation of our or third parties' intellectual property and other proprietary rights, which may subject you to civil liability and/or criminal prosecution.</Text>
    </View>
    <View className="px-3 justify-center">
    <Text className="text-blue-400 text-2xl font-psemibold">4. USAGE BY THOSE UNDER THE AGE OF 18 YEARS</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">
     If we suspect that you are or receive notification that you are currently under 18 years or were under 18 years (or below the age of majority as stipulated in the laws of the jurisdiction applicable to you) when you played any game through our Service, your Account will be suspended (locked) to prevent you from playing further or making any withdrawals from your Account. We will then investigate the matter, including whether you have been playing the game as an agent for, or otherwise on behalf, of a person under 18 years (or below the age of majority as stipulated in the laws of the jurisdiction applicable to you). If, having found that you: (a) are currently; (b) were under 18 years or below the majority age which applies to you at the relevant time; or (c) have been at the behest of a person under 18 years or below the majority age, wherein:</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 all winnings currently or due to be credited to your Account will be retained;`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 all winnings gained from playing through the Service whilst acting as an agent to someone underage must be paid to us on demand (if you fail to comply with this provision, we will seek to recover all costs associated with recovery of such sums); and/or`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 any monies deposited in your Account which are not winnings will be returned to you OR retained until you turn 18 years old at our sole discretion. We reserve the right to deduct payment transaction fees from the amount to return, including maintenance fees for deposits to your account, which we may retain.`}</Text>
     <Text className="text-blue-200 text-2xs px-2 my-4 items-center">In the event we suspect you are in breach of the provisions of this Clause or are attempting to rely on them for a fraudulent purpose, we reserve the right to take any action necessary in order to investigate the matter, including informing the relevant law enforcement agencies.</Text>
    </View>

    <View className="px-3 justify-center">
    <Text className="text-blue-400 text-2xl font-psemibold">5. USERS' CONDUCT</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Users agree to abide by the following stipulated rules, regulations, and terms of use of the Website. In the event, that the User does not abide by these following rules, regulations, and terms of use, Ludo Empire may, at its sole and absolute discretion, take necessary remedial action, including but not limited to, restricting, suspending, or terminating any User's access to all or any part of Ludo Empire's Services;</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 Deactivating or deleting a user's account and all related information and files on the account. Any amount remaining unused in the User's Game account or Winnings Account on the date of deactivation or deletion shall be transferred to the User's bank account on record with Ludo Empire, subject to a processing fee (if any) applicable on such transfers as set out herein; or`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 refraining from awarding any prize(s) to such User.`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 Users agree to provide true, accurate, current, and complete information at the time of registration and at all other times (as required by Ludo Empire). Users further agree to update and keep updated their registration information.`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 A User shall not register or operate more than one User account with Ludo Empire.`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 Users agree to ensure that they can receive all communication from Ludo Empire by marking emails from Ludo Empire as part of their "safe senders" list. Ludo Empire shall not be held liable if any email remains unread by a User as a result of such e-mail getting delivered to the User's junk or spam folder.`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 Any password issued by Ludo Empire to a User may not be revealed to anyone else. Users may not use anyone else's password. Users are responsible for maintaining the confidentiality of their accounts and passwords. Users agree to immediately notify Ludo Empire of any unauthorized use of their passwords or accounts or any other breach of security.`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 Users agree to exit/log out of their accounts at the end of each session. Ludo Empire shall not be responsible for any loss or damage that may result if the User fails to comply with these requirements.`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 Users agree not to use cheats, exploits, automation, software, bots, hacks, or any unauthorized third-party software designed to modify or interfere with Ludo Empire's Services and/or Ludo Empire experience or assist in such activity.`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 Users agree not to copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer, grant a security interest in, or otherwise transfer any right to the technology or software underlying Ludo Empire or Ludo Empire's Services.`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 Users agree not to disrupt, overburden, or aid or assist in the disruption or overburdening of (1) any computer or server used to offer or support Ludo Empire or the Ludo Empire's Services (each a "Server"); or (2) the enjoyment of Ludo Empire's Services by any other User or person`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 Users agree not to institute, assist or become involved in any type of attack, including without limitation, distribution of a virus, denial of service, or other attempts to disrupt Ludo Empire's Services or any other person's use or enjoyment of Ludo Empire's Services.`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 Users shall not attempt to gain unauthorized access to the User accounts, Servers or networks connected to Ludo Empire's Services by any means other than the User interface provided by Ludo Empire, including but not limited to, circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that underlies or is part of Ludo Empire's Services.`}</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Without limiting the foregoing, Users agree not to use Ludo Empire for any of the following:</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To engage in any obscene, offensive, indecent, racial, communal, anti-national, objectionable, defamatory, or abusive action or communication;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To harass, stalk, threaten, or otherwise violate any legal rights of other individuals;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To publish, post, upload, e-mail, distribute, or disseminate (collectively, "Transmit") any inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful content;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To Transmit files that contain viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another person's computer, Ludo Empire, any software, hardware, or telecommunications equipment;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To advertise, engage in or execute any contingent agreement with the outcomes of Ludo Empire;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To Transmit content regarding services, products, surveys, contests, pyramid schemes, spam, unsolicited advertising or promotional materials, or chain letters;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To advertise, offer or sell any goods or services for any commercial purpose claiming to be from Ludo Empire without the express written consent of Ludo Empire;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To download any file, recompile or disassemble or otherwise affect our products that you know or reasonably should know cannot be legally obtained in such manner;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or the source of software or other material;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To restrict or inhibit any other user from using and enjoying any public area within our sites;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To collect or store personal information about other Users;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To interfere with or disrupt Ludo Empire, servers, or networks;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To impersonate any person or entity, including, but not limited to, a representative of Ludo Empire, or falsely state or otherwise misrepresent User's affiliation with a person or entity;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To forge headers or manipulate identifiers or other data in order to disguise the origin of any content transmitted through Ludo Empire or to manipulate the User's presence on Ludo Empire;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To take any action that imposes an unreasonably or disproportionately large load on our infrastructure;`}</Text>
    <Text className="text-lg text-blue-200">{`\u25C9 To engage in any illegal activities. You agree to use our bulletin board services, chat areas, news groups, forums, communities and/or message or communication facilities (collectively, the "Forums") only to send and receive messages and material that are proper and related to that particular Forum.`}</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">If a User chooses a username that, in Ludo Empire's considered opinion is obscene, indecent, abusive or that might subject Ludo Empire to public disparagement or scorn, Ludo Empire reserves the right, without prior notice to the User, to change such username and intimate the User or delete such username from Ludo Empire, and/or deny such User access to Ludo Empire, or any combination of these options.</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Unauthorized access to Ludo Empire is a breach of these Terms and Conditions, and a violation of the law. Users agree not to access Ludo Empire by any means other than through the interface that is provided by Ludo Empire for use in accessing Ludo Empire. Users agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of our app.</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">The use of Ludo Empire is subject to existing laws and legal processes. Nothing contained in these Terms and Conditions shall limit Ludo Empire's right to comply with government, court, and law-enforcement requests or requirements relating to Users' usage of Ludo Empire.</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Users may contact Ludo Empire's Helpdesk with problems or questions, as appropriate.</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Persons below the age of eighteen (18) years are not allowed to play/register/use any of the Ludo Empire & consequent participation in any activity on Ludo Empire is not permitted and such person is subject to disqualification at the sole and absolute discretion of Ludo Empire, whenever it comes to the knowledge of Ludo Empire.</Text>
    <Text className="text-blue-400 text-2xl font-psemibold">PLAY RESPONSIBLY</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Ludo Empire may involve an element of financial risk and may be habit-forming. Please play responsibly and at your own risk.</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">During gameplay, please be aware of your surroundings and play safely. You agree that your use of the apps and play of the games is at your own risk, and it is your responsibility to maintain such health, liability, medical life, and other insurance policies as you deem reasonably necessary for any injuries that you may incur while using the services. You also agree not to use the Apps to violate any applicable law, rule, or regulation or the guidelines and how to play, and you agree not to encourage or enable any other individual to violate any applicable law, rule or regulation, or the guidelines. Without limiting the foregoing, you agree that in conjunction with your use of the Apps, you will not inflict emotional distress on other people, will not humiliate other people (publicly or otherwise), will not assault, or threaten people, will not impersonate any other person or misrepresent your affiliation, title or authority, and will not otherwise engage in activity that may result in injury, self-harm, habit-forming patterns, and/or liability of any kind. Ludo Empire and its developers disclaim liability related to injury, self-harm, and/or habit-forming patterns that may occur during your use of our services, including any claims based on the violation of any applicable law, rule or regulation or your alleged negligence or other tort liability.</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">If you believe that you are forming a habit of gaming which is problematic, notify Ludo Empire by email or through the in-game live Hosts, if provided. Ludo Empire policy does not provide you with an option to self-set or change deposit limits at your discretion; rather your identity will be confirmed, and your account will be closed for real money gaming activity, for a prescribed period. Ludo Empire reserves the absolute right, to itself, to review or use third-party verification to review player activity in the Games or as reported by other gaming operators to profile and remove a player's access in its sole discretion.</Text>
    <Text className="text-blue-200 text-2xs px-2 my-4 items-center">These are some general guidelines that can help make your playing experience safer, and avoid the risk that you may indulge in excessive gaming and addiction:</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 Add money to the Ludo Empire's Wallets only with money that you can afford to spend.`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 Please, never add money to the account Wallets with money that you need for important or essential things such as food, rent, day-to-day bills, medical assistance or education.`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 Pre-plan your purchases and the time you will spend playing on the Websites and stick to that limit, regardless of your performance.`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 Do not play when you are upset, tired, or depressed. It is difficult to make good decisions when you are not feeling well.`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 Do not put off personal and other important tasks in order to play. Complete all your important tasks so that you can play with a free and calm mind.`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 Balance your gameplay duration with other activities.`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 Do not borrow money in order to make purchases on the Websites.`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 Avoid using all the monies in the game wallets in a single game or session.`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 Take time-outs and breaks regularly.`}</Text>
     <Text className="text-lg text-blue-200">{`\u25C9 Only participate in games that are commensurate with your competence level and financial capabilities. Do not get tempted to participate in games with high entry fees, despite winning consistently.`}</Text>
     <Text className="text-blue-200 text-2xs px-2 my-4 items-center">Further, in the event that you have a dispute with one or more other users of the apps, or any other third party while using the services, you release Ludo Empire and its developers from all claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, suspected, and unsuspected, disclosed, and undisclosed, arising out of or in a way connected with such disputes.</Text>
    </View>
    
    
    </ScrollView> 
    </SafeAreaView>
  )
}

export default Terms

const styles = StyleSheet.create({})